### ISSUE TITLE
Open file via url

### ISSUE THREAD

**Issue by ArmandArthur** [cubiclesoft/php-filemanager#2]
Hello,

For beginning, GREAT JOB!

I would to know if it's possible to open file via a path URL?

Thx

**Comment by cubiclesoft** [comment]
Do you mean entering a generic URL and seeing the code in the editor?

One option is to upload the returned contents for a URL via your OS' built-in file manager.  At least on Windows, click the upload icon to start uploading a file and then paste a URL into the filename field.  Windows will transparently download the URL and then upload it to the server.  Opening the file from the server in the tool is possible at that point.

Creating an `index_hook.php` file overrides the built-in login system and can optionally inject custom modifications of the interface.

**Comment by ArmandArthur** [comment]
Do you mean entering a generic URL and seeing the code in the editor? YES

Exemple:

URL/php-filemanager?file=myFile.php

**Comment by ArmandArthur** [comment]
What I Do take in the index_hook.php? The GET parameter?

How trigger the click on the file after?

**Comment by cubiclesoft** [comment]
Caveat:  Editing PHP files in a web browser connected to a web server that executes PHP code carries significant security risks.  Anyone who gains access to the interface can upload and then execute whatever PHP files they want to.  CubicleSoft is not responsible for how you decide to use this software (as per the license) but you should probably reconsider editing PHP files in a web browser as a generally bad idea.

With that warning out of the way, I still think the built-in OS mechanism for download/upload is the best way to go.  And if you want to do it in a web interface, you should probably use a different script to retrieve a URL to store on the server and defend appropriately against bad actors.  Then you can probably redirect to PHP File Manager and use `index_hook.php` to open the folder containing the downloaded file.

There is no mechanism to automatically open a specific file in the editor at startup.  The 'fe_initpath' option can make File Explorer go to a specific folder.  While the File Explorer widget has the ability to programmatically trigger selection and opening specific items, there are no hooks for that functionality at the PHP File Manager level.  Considering the security risks involved, I'm not inclined to add such hooks to enable such functionality.

**Comment by ArmandArthur** [comment]
Bad idea yes but i need to edit files php in brower. 

I will not implement the "open file", i will find others soluions.

I have secured the folder with htaccess/htpasswd

**Comment by ArmandArthur** [comment]
Maybe more with a authentification php.
