### ISSUE TITLE
Drag & Drop to move into folder

### ISSUE THREAD

**Issue by RoyBellingan** [cubiclesoft/php-filemanager#3]
Hi, nice widget! And thank you for the insight on the creation.

The only thing I am missing is the drag & drop to move inside a file, which work in the https://github.com/cubiclesoft/js-fileexplorer demo.

Is something to add, tweak in the config ?

**Comment by cubiclesoft** [comment]
Hmm...using drag and drop to move files into folders seems to work fine in my test environment on Windows in Firefox.  I don't think there a server side configuration item for that.

Some more information might be helpful to replicate.

**Comment by RoyBellingan** [comment]
uhm, I will try in this case on more machine.

**Comment by cubiclesoft** [comment]
Closing this issue.  If you can come up with steps to replicate the problem, I'll reopen it again.
